use serde::{Deserialize, Serialize};

/// WorkspaceInfo — Describes the current workspace state.
///
/// Mirrors the frontend `WorkspaceInfo` TypeScript interface.
///
/// TODO: Populated by workspace::load_workspace in a future phase.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WorkspaceInfo {
    pub root_path: String,
    pub display_name: String,
    pub is_available: bool,
    pub file_count: u64,
    pub last_indexed_at: Option<String>,
}

/// IndexEntry — A single Markdown file entry in the workspace index.
///
/// Mirrors the frontend `IndexEntry` TypeScript interface.
///
/// TODO: Generated by the indexer module in a future phase.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct IndexEntry {
    pub id: String,
    pub name: String,
    pub absolute_path: String,
    pub relative_path: String,
    pub parent_relative_path: String,
    pub extension: String, // "md" | "markdown"
    pub updated_at: Option<String>,
    pub size: Option<u64>,
}

/// IndexTreeNode — A node in the workspace index tree.
///
/// Mirrors the frontend `IndexTreeNode` TypeScript interface.
///
/// TODO: Built by the indexer module in a future phase.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct IndexTreeNode {
    pub id: String,
    pub name: String,
    #[serde(rename = "type")]
    pub node_type: String, // "directory" | "file"
    pub relative_path: String,
    pub children: Option<Vec<IndexTreeNode>>,
    pub entry: Option<IndexEntry>,
}

/// WorkspaceLoadResult — Returned by select_workspace / load_workspace.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WorkspaceLoadResult {
    pub workspace: WorkspaceInfo,
    pub index_tree: Vec<IndexTreeNode>,
    pub flat_entries: Vec<IndexEntry>,
    pub restored_document_path: Option<String>,
}

/// WorkspaceIndexResult — Returned by refresh_workspace_index.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WorkspaceIndexResult {
    pub workspace: WorkspaceInfo,
    pub index_tree: Vec<IndexTreeNode>,
    pub flat_entries: Vec<IndexEntry>,
}